server {
    listen 18080;
    listen [::]:18080;
    server_name _;

    client_max_body_size 60m;

    location /static/images/ {
        alias /opt/rainbow-backend/uploads/test/images/;
        try_files $uri =404;
    }

    location /static/audio/ {
        alias /opt/rainbow-backend/uploads/test/audio/;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://127.0.0.1:18081;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}

server {
    listen 28080;
    listen [::]:28080;
    server_name _;

    client_max_body_size 60m;

    location /static/images/ {
        alias /opt/rainbow-backend/uploads/prod/images/;
        try_files $uri =404;
    }

    location /static/audio/ {
        alias /opt/rainbow-backend/uploads/prod/audio/;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://127.0.0.1:28081;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}
